schemaVersion: 2.1.0
metadata:
  name: go-hello-world-sample
attributes:
  controller.devfile.io/storage-type: ephemeral
components:
  - name: api-2 
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 4Gi
      memoryRequest: 256Mi
  - name: projects
    volume: {ephemeral: true}
