schemaVersion: 2.1.0
metadata:
  name: universal-space
components:
  - name: universal-tooling-container
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-0e189d9
      endpoints:
        - name: webapp
          targetPort: 8080
      memoryLimit: 4Gi
  - name: projects
    volume:
      size: 3Gi
